[profile.default]
solc = '0.8.22'
evm_version='paris'
via_ir = true
src = 'src'
out = 'out'
test = 'test'
libs = ['lib']
optimizer = true
optimizer_runs = 900
ignored_error_codes = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
